apiVersion: v1
kind: Service
metadata:
  name: frame-postgre-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: frame-postgre
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: flask
    port: 5000
    targetPort: 5000
    protocol: TCP
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
