apiVersion: v1
kind: Pod
metadata:
  name: ansible
spec:
  containers:
    - name: ansible
      image: willhallonline/ansible:latest
      command: ["sleep", "36000"]
      volumeMounts:
        - name: ansible-volume
          mountPath: /ansible
  volumes:
    - name: ansible-volume
      hostPath:
        path: /Users/bala/k8s/ansible
