apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    appendonly yes
    appendfilename "appendonly.aof"
    dir /data
    dbfilename dump.rdb
    save 900 1
    save 300 10
    save 60 10000
    maxmemory 512mb
    maxmemory-policy volatile-lru
    maxclients 1000
    tcp-keepalive 300
    protected-mode no
